from django.db import models


class SysOrg(models.Model):
    org_id = models.AutoField(primary_key=True, db_column="ORGID")
    dem_id = models.IntegerField(db_column="DEMID")
    org_name = models.CharField(max_length=128, db_column="ORGNAME")
    org_desc = models.CharField(max_length=128, db_column="ORGDESC")
    org_sup_id = models.IntegerField(db_column="ORGSUPID")
    path = models.CharField(max_length=128, db_column="PATH")
    depth = models.IntegerField(db_column="DEPTH")
    org_type = models.IntegerField(db_column="ORGTYPE")
    creator_id = models.IntegerField(db_column="CREATORID")
    create_time = models.DateTimeField(db_column="CREATETIME")
    update_id = models.IntegerField(db_column="UPDATEID")
    update_time = models.DateTimeField(db_column="UPDATETIME")
    sn = models.IntegerField(db_column="SN")
    from_type = models.IntegerField(db_column="FROMTYPE")
    org_path_name = models.CharField(max_length=2000, db_column="ORGPATHNAME")
    is_delete = models.IntegerField()
    code = models.IntegerField()
    company_id = models.IntegerField(db_column="COMPANYID")
    company_name = models.CharField(max_length=20, db_column="COMPANY")
    org_staff = models.IntegerField(db_column="ORGSTAFF")
    org_code = models.CharField(max_length=200, db_column="ORGCODE")
    org_levels = models.IntegerField()
    org_short_name = models.CharField(max_length=255)
    hr_id = models.CharField(max_length=50, db_column="HRID")
    is_company = models.IntegerField()
    # is_executed = models.IntegerField()
    common_org_id = models.IntegerField()
    legal_person = models.IntegerField()
    legal_person_name = models.CharField(max_length=200)
    dep_type = models.CharField(max_length=100)
    dep_strip_line = models.CharField(max_length=100)
    org_type_name = models.CharField(max_length=255)
    dep_level = models.CharField(max_length=255)
    dep_area = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=100)
    hr_id = models.IntegerField()
